### ISSUE TITLE
Run error with version `GLIBC_2.34' not found

### ISSUE THREAD

**Issue by Css22** [pkusys/TGS#5]
我成功pull了你的docker镜像同时完成了环境的配置，然而运行时报错：
```
Traceback (most recent call last):
  File "worker.py", line 264, in <module>
    finished_tasks = worker.check_tasks()
  File "worker.py", line 139, in check_tasks
    assert task._finished_iterations == task._iterations
AssertionError
```
我进行了错误排查，发现docker中对任务的执行时报错：
```
bash: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /libcontroller.so)
bash: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /libcontroller.so)
bash: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /libcuda.so)
bash: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /libcuda.so)
bash: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /libcuda.so.1)
bash: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /libcuda.so.1)
bash: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /libnvidia-ml.so)
bash: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /libnvidia-ml.so)
bash: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /libnvidia-ml.so.1)
bash: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /libnvidia-ml.so.1)
```
执行的脚本是`./scripts/test_tgs.sh`。

**Comment by 1l1l1ll1** [comment]
您好，我也是这个问题。请问解决了吗

**Comment by LepingLi0810** [comment]
这个问题是host machine和container glibc version mismatch导致的，在host machine上编译好的.so files mount进container里用不了，解决方法就是不直接把.so files mount进去，在container里面自己build
